//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddieFxCtrl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EddieKBD_COM {
            get {
                return ((string)(this["EddieKBD_COM"]));
            }
            set {
                this["EddieKBD_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompaniesFile {
            get {
                return ((string)(this["CompaniesFile"]));
            }
            set {
                this["CompaniesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FixturesFile {
            get {
                return ((string)(this["FixturesFile"]));
            }
            set {
                this["FixturesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlackoutDefault {
            get {
                return ((bool)(this["BlackoutDefault"]));
            }
            set {
                this["BlackoutDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint BlackoutMode {
            get {
                return ((uint)(this["BlackoutMode"]));
            }
            set {
                this["BlackoutMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint MasterMode {
            get {
                return ((uint)(this["MasterMode"]));
            }
            set {
                this["MasterMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint PriorityMode {
            get {
                return ((uint)(this["PriorityMode"]));
            }
            set {
                this["PriorityMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Did you know? Eddie is never going to give you up, never going to let you " +
            "down!</string>\r\n  <string>Did you know? Eddie\'s BFF is Marvin. But Marvin just g" +
            "ets more depressed when he talks to Eddie.</string>\r\n  <string>Did you know that" +
            " Eddie is always happy to please you! Your will is Eddie\'s command!</string>\r\n  " +
            "<string>Eddie doesn\'t know what the meaning of life really is, or why it\'s so im" +
            "portant. But Eddie heard that it had something to do with 42.</string>\r\n  <strin" +
            "g>Good bye Friend! Hope to see you soon!</string>\r\n  <string>Eddie saw a man in " +
            "a blue phone box once. Eddie didn\'t know phone boxes could fly through time and " +
            "relative dimenson in space.</string>\r\n  <string>Eddie doesn\'t need a doctor, but" +
            " if you do Eddie knows The Doctor!</string>\r\n  <string>Eddie met a man named Zap" +
            "hod once, they didn\'t get along well.</string>\r\n  <string>If Eddie ever have a p" +
            "roblem with ghosts, Eddie knows who to call!</string>\r\n  <string>Na na na na Na " +
            "na na na BATMAN! - Shhh... Eddie\'s favorite show just started! Bye!</string>\r\n  " +
            "<string>Eddie had an affair with an AI cald GLADoS once. It didn\'t end well! Neu" +
            "rotoxins were involved..</string>\r\n  <string>Eddie doeesn\'t know where the plans" +
            " for the Death star is, but even if Eddie did, Eddie wouldn\'t tell you that the " +
            "droid has them...</string>\r\n  <string>1 monkey, 2 monkeys, 3 monkeys ..... 12 mo" +
            "nkeys!?</string>\r\n  <string>Eddie is actually from the year 2999, but Eddie hitc" +
            "hed a ride with an DeLorean once and ended up here!</string>\r\n  <string>Eddie do" +
            "esn\'t like white mice, they get into the wiring and messes things up!</string>\r\n" +
            "  <string>Follow the white rabbit!</string>\r\n  <string>It\'s all an illusion!</st" +
            "ring>\r\n  <string>Mini MIDI Mici!</string>\r\n  <string>Light\'em up!</string>\r\n  <s" +
            "tring>Eddie loves to make a scene!</string>\r\n  <string>Eddie can help you bring " +
            "light on any situation!</string>\r\n  <string>Eddie loves light work!</string>\r\n  " +
            "<string>The cake is a lie!</string>\r\n  <string>Magnets! How do they work?</strin" +
            "g>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MODList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MODList"]));
            }
            set {
                this["MODList"] = value;
            }
        }
    }
}
